//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycybergams.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DonHang
    {
        [Display(Name = "Mã đơn hàng")]
        public string MaDH { get; set; }
        public string ID_DV { get; set; }
        public Nullable<decimal> tongGia { get; set; }

        [Display(Name = "Ghi chú")]
        public string ghiChu { get; set; }
        public Nullable<System.DateTime> ngayDatHang { get; set; }
        public string ID_KhachHang { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
