//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("QuanLyCYBERGAMESModel", "FK__DichVu__ID_Matha__3F466844", "Kho", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(quanlycybergams.Models.Kho), "DichVu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(quanlycybergams.Models.DichVu), true)]
[assembly: EdmRelationshipAttribute("QuanLyCYBERGAMESModel", "FK__DonHang__ID_DV__4316F928", "DichVu", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(quanlycybergams.Models.DichVu), "DonHang", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(quanlycybergams.Models.DonHang), true)]
[assembly: EdmRelationshipAttribute("QuanLyCYBERGAMESModel", "FK__May__ID_gia__3A81B327", "DonGia", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(quanlycybergams.Models.DonGia), "May", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(quanlycybergams.Models.May), true)]
[assembly: EdmRelationshipAttribute("QuanLyCYBERGAMESModel", "FK__DonHang__ID_Khac__4222D4EF", "TaiKhoan", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(quanlycybergams.Models.TaiKhoan), "DonHang", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(quanlycybergams.Models.DonHang), true)]
[assembly: EdmRelationshipAttribute("QuanLyCYBERGAMESModel", "FK__HoaDon__ID_Khach__48CFD27E", "TaiKhoan", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(quanlycybergams.Models.TaiKhoan), "HoaDon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(quanlycybergams.Models.HoaDon), true)]
[assembly: EdmRelationshipAttribute("QuanLyCYBERGAMESModel", "FK__HoaDon__ID_May__4AB81AF0", "May", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(quanlycybergams.Models.May), "HoaDon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(quanlycybergams.Models.HoaDon), true)]
[assembly: EdmRelationshipAttribute("QuanLyCYBERGAMESModel", "FK__HoaDon__ID_TTDV__49C3F6B7", "ThanhToanDV", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(quanlycybergams.Models.ThanhToanDV), "HoaDon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(quanlycybergams.Models.HoaDon), true)]
[assembly: EdmRelationshipAttribute("QuanLyCYBERGAMESModel", "FK__ThanhToan__ID_Kh__45F365D3", "TaiKhoan", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(quanlycybergams.Models.TaiKhoan), "ThanhToanDV", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(quanlycybergams.Models.ThanhToanDV), true)]

#endregion

namespace quanlycybergams.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QuanLyCYBERGAMESEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QuanLyCYBERGAMESEntities1 object using the connection string found in the 'QuanLyCYBERGAMESEntities1' section of the application configuration file.
        /// </summary>
        public QuanLyCYBERGAMESEntities1() : base("name=QuanLyCYBERGAMESEntities1", "QuanLyCYBERGAMESEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuanLyCYBERGAMESEntities1 object.
        /// </summary>
        public QuanLyCYBERGAMESEntities1(string connectionString) : base(connectionString, "QuanLyCYBERGAMESEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuanLyCYBERGAMESEntities1 object.
        /// </summary>
        public QuanLyCYBERGAMESEntities1(EntityConnection connection) : base(connection, "QuanLyCYBERGAMESEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DichVu> DichVus
        {
            get
            {
                if ((_DichVus == null))
                {
                    _DichVus = base.CreateObjectSet<DichVu>("DichVus");
                }
                return _DichVus;
            }
        }
        private ObjectSet<DichVu> _DichVus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DonGia> DonGias
        {
            get
            {
                if ((_DonGias == null))
                {
                    _DonGias = base.CreateObjectSet<DonGia>("DonGias");
                }
                return _DonGias;
            }
        }
        private ObjectSet<DonGia> _DonGias;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DonHang> DonHangs
        {
            get
            {
                if ((_DonHangs == null))
                {
                    _DonHangs = base.CreateObjectSet<DonHang>("DonHangs");
                }
                return _DonHangs;
            }
        }
        private ObjectSet<DonHang> _DonHangs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HoaDon> HoaDons
        {
            get
            {
                if ((_HoaDons == null))
                {
                    _HoaDons = base.CreateObjectSet<HoaDon>("HoaDons");
                }
                return _HoaDons;
            }
        }
        private ObjectSet<HoaDon> _HoaDons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Kho> Khoes
        {
            get
            {
                if ((_Khoes == null))
                {
                    _Khoes = base.CreateObjectSet<Kho>("Khoes");
                }
                return _Khoes;
            }
        }
        private ObjectSet<Kho> _Khoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<May> Mays
        {
            get
            {
                if ((_Mays == null))
                {
                    _Mays = base.CreateObjectSet<May>("Mays");
                }
                return _Mays;
            }
        }
        private ObjectSet<May> _Mays;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TaiKhoan> TaiKhoans
        {
            get
            {
                if ((_TaiKhoans == null))
                {
                    _TaiKhoans = base.CreateObjectSet<TaiKhoan>("TaiKhoans");
                }
                return _TaiKhoans;
            }
        }
        private ObjectSet<TaiKhoan> _TaiKhoans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ThanhToanDV> ThanhToanDVs
        {
            get
            {
                if ((_ThanhToanDVs == null))
                {
                    _ThanhToanDVs = base.CreateObjectSet<ThanhToanDV>("ThanhToanDVs");
                }
                return _ThanhToanDVs;
            }
        }
        private ObjectSet<ThanhToanDV> _ThanhToanDVs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DichVus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDichVus(DichVu dichVu)
        {
            base.AddObject("DichVus", dichVu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DonGias EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDonGias(DonGia donGia)
        {
            base.AddObject("DonGias", donGia);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DonHangs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDonHangs(DonHang donHang)
        {
            base.AddObject("DonHangs", donHang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HoaDons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHoaDons(HoaDon hoaDon)
        {
            base.AddObject("HoaDons", hoaDon);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Khoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKhoes(Kho kho)
        {
            base.AddObject("Khoes", kho);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Mays EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMays(May may)
        {
            base.AddObject("Mays", may);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TaiKhoans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTaiKhoans(TaiKhoan taiKhoan)
        {
            base.AddObject("TaiKhoans", taiKhoan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ThanhToanDVs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToThanhToanDVs(ThanhToanDV thanhToanDV)
        {
            base.AddObject("ThanhToanDVs", thanhToanDV);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyCYBERGAMESModel", Name="DichVu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DichVu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DichVu object.
        /// </summary>
        /// <param name="iD_DV">Initial value of the ID_DV property.</param>
        public static DichVu CreateDichVu(global::System.String iD_DV)
        {
            DichVu dichVu = new DichVu();
            dichVu.ID_DV = iD_DV;
            return dichVu;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_DV
        {
            get
            {
                return _ID_DV;
            }
            set
            {
                if (_ID_DV != value)
                {
                    OnID_DVChanging(value);
                    ReportPropertyChanging("ID_DV");
                    _ID_DV = StructuralObject.SetValidValue(value, false, "ID_DV");
                    ReportPropertyChanged("ID_DV");
                    OnID_DVChanged();
                }
            }
        }
        private global::System.String _ID_DV;
        partial void OnID_DVChanging(global::System.String value);
        partial void OnID_DVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenDV
        {
            get
            {
                return _TenDV;
            }
            set
            {
                OnTenDVChanging(value);
                ReportPropertyChanging("TenDV");
                _TenDV = StructuralObject.SetValidValue(value, true, "TenDV");
                ReportPropertyChanged("TenDV");
                OnTenDVChanged();
            }
        }
        private global::System.String _TenDV;
        partial void OnTenDVChanging(global::System.String value);
        partial void OnTenDVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AnhSP
        {
            get
            {
                return _AnhSP;
            }
            set
            {
                OnAnhSPChanging(value);
                ReportPropertyChanging("AnhSP");
                _AnhSP = StructuralObject.SetValidValue(value, true, "AnhSP");
                ReportPropertyChanged("AnhSP");
                OnAnhSPChanged();
            }
        }
        private global::System.String _AnhSP;
        partial void OnAnhSPChanging(global::System.String value);
        partial void OnAnhSPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> GiaBan
        {
            get
            {
                return _GiaBan;
            }
            set
            {
                OnGiaBanChanging(value);
                ReportPropertyChanging("GiaBan");
                _GiaBan = StructuralObject.SetValidValue(value, "GiaBan");
                ReportPropertyChanged("GiaBan");
                OnGiaBanChanged();
            }
        }
        private Nullable<global::System.Decimal> _GiaBan;
        partial void OnGiaBanChanging(Nullable<global::System.Decimal> value);
        partial void OnGiaBanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID_Mathang
        {
            get
            {
                return _ID_Mathang;
            }
            set
            {
                OnID_MathangChanging(value);
                ReportPropertyChanging("ID_Mathang");
                _ID_Mathang = StructuralObject.SetValidValue(value, true, "ID_Mathang");
                ReportPropertyChanged("ID_Mathang");
                OnID_MathangChanged();
            }
        }
        private global::System.String _ID_Mathang;
        partial void OnID_MathangChanging(global::System.String value);
        partial void OnID_MathangChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyCYBERGAMESModel", "FK__DichVu__ID_Matha__3F466844", "Kho")]
        public Kho Kho
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kho>("QuanLyCYBERGAMESModel.FK__DichVu__ID_Matha__3F466844", "Kho").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kho>("QuanLyCYBERGAMESModel.FK__DichVu__ID_Matha__3F466844", "Kho").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Kho> KhoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kho>("QuanLyCYBERGAMESModel.FK__DichVu__ID_Matha__3F466844", "Kho");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Kho>("QuanLyCYBERGAMESModel.FK__DichVu__ID_Matha__3F466844", "Kho", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyCYBERGAMESModel", "FK__DonHang__ID_DV__4316F928", "DonHang")]
        public EntityCollection<DonHang> DonHangs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DonHang>("QuanLyCYBERGAMESModel.FK__DonHang__ID_DV__4316F928", "DonHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DonHang>("QuanLyCYBERGAMESModel.FK__DonHang__ID_DV__4316F928", "DonHang", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyCYBERGAMESModel", Name="DonGia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DonGia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DonGia object.
        /// </summary>
        /// <param name="iD_gia">Initial value of the ID_gia property.</param>
        public static DonGia CreateDonGia(global::System.String iD_gia)
        {
            DonGia donGia = new DonGia();
            donGia.ID_gia = iD_gia;
            return donGia;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_gia
        {
            get
            {
                return _ID_gia;
            }
            set
            {
                if (_ID_gia != value)
                {
                    OnID_giaChanging(value);
                    ReportPropertyChanging("ID_gia");
                    _ID_gia = StructuralObject.SetValidValue(value, false, "ID_gia");
                    ReportPropertyChanged("ID_gia");
                    OnID_giaChanged();
                }
            }
        }
        private global::System.String _ID_gia;
        partial void OnID_giaChanging(global::System.String value);
        partial void OnID_giaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> GiaMay
        {
            get
            {
                return _GiaMay;
            }
            set
            {
                OnGiaMayChanging(value);
                ReportPropertyChanging("GiaMay");
                _GiaMay = StructuralObject.SetValidValue(value, "GiaMay");
                ReportPropertyChanged("GiaMay");
                OnGiaMayChanged();
            }
        }
        private Nullable<global::System.Decimal> _GiaMay;
        partial void OnGiaMayChanging(Nullable<global::System.Decimal> value);
        partial void OnGiaMayChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyCYBERGAMESModel", "FK__May__ID_gia__3A81B327", "May")]
        public EntityCollection<May> Mays
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<May>("QuanLyCYBERGAMESModel.FK__May__ID_gia__3A81B327", "May");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<May>("QuanLyCYBERGAMESModel.FK__May__ID_gia__3A81B327", "May", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyCYBERGAMESModel", Name="DonHang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DonHang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DonHang object.
        /// </summary>
        /// <param name="maDH">Initial value of the MaDH property.</param>
        public static DonHang CreateDonHang(global::System.String maDH)
        {
            DonHang donHang = new DonHang();
            donHang.MaDH = maDH;
            return donHang;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaDH
        {
            get
            {
                return _MaDH;
            }
            set
            {
                if (_MaDH != value)
                {
                    OnMaDHChanging(value);
                    ReportPropertyChanging("MaDH");
                    _MaDH = StructuralObject.SetValidValue(value, false, "MaDH");
                    ReportPropertyChanged("MaDH");
                    OnMaDHChanged();
                }
            }
        }
        private global::System.String _MaDH;
        partial void OnMaDHChanging(global::System.String value);
        partial void OnMaDHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID_DV
        {
            get
            {
                return _ID_DV;
            }
            set
            {
                OnID_DVChanging(value);
                ReportPropertyChanging("ID_DV");
                _ID_DV = StructuralObject.SetValidValue(value, true, "ID_DV");
                ReportPropertyChanged("ID_DV");
                OnID_DVChanged();
            }
        }
        private global::System.String _ID_DV;
        partial void OnID_DVChanging(global::System.String value);
        partial void OnID_DVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> tongGia
        {
            get
            {
                return _tongGia;
            }
            set
            {
                OntongGiaChanging(value);
                ReportPropertyChanging("tongGia");
                _tongGia = StructuralObject.SetValidValue(value, "tongGia");
                ReportPropertyChanged("tongGia");
                OntongGiaChanged();
            }
        }
        private Nullable<global::System.Decimal> _tongGia;
        partial void OntongGiaChanging(Nullable<global::System.Decimal> value);
        partial void OntongGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ghiChu
        {
            get
            {
                return _ghiChu;
            }
            set
            {
                OnghiChuChanging(value);
                ReportPropertyChanging("ghiChu");
                _ghiChu = StructuralObject.SetValidValue(value, true, "ghiChu");
                ReportPropertyChanged("ghiChu");
                OnghiChuChanged();
            }
        }
        private global::System.String _ghiChu;
        partial void OnghiChuChanging(global::System.String value);
        partial void OnghiChuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ngayDatHang
        {
            get
            {
                return _ngayDatHang;
            }
            set
            {
                OnngayDatHangChanging(value);
                ReportPropertyChanging("ngayDatHang");
                _ngayDatHang = StructuralObject.SetValidValue(value, "ngayDatHang");
                ReportPropertyChanged("ngayDatHang");
                OnngayDatHangChanged();
            }
        }
        private Nullable<global::System.DateTime> _ngayDatHang;
        partial void OnngayDatHangChanging(Nullable<global::System.DateTime> value);
        partial void OnngayDatHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID_KhachHang
        {
            get
            {
                return _ID_KhachHang;
            }
            set
            {
                OnID_KhachHangChanging(value);
                ReportPropertyChanging("ID_KhachHang");
                _ID_KhachHang = StructuralObject.SetValidValue(value, true, "ID_KhachHang");
                ReportPropertyChanged("ID_KhachHang");
                OnID_KhachHangChanged();
            }
        }
        private global::System.String _ID_KhachHang;
        partial void OnID_KhachHangChanging(global::System.String value);
        partial void OnID_KhachHangChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyCYBERGAMESModel", "FK__DonHang__ID_DV__4316F928", "DichVu")]
        public DichVu DichVu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DichVu>("QuanLyCYBERGAMESModel.FK__DonHang__ID_DV__4316F928", "DichVu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DichVu>("QuanLyCYBERGAMESModel.FK__DonHang__ID_DV__4316F928", "DichVu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DichVu> DichVuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DichVu>("QuanLyCYBERGAMESModel.FK__DonHang__ID_DV__4316F928", "DichVu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DichVu>("QuanLyCYBERGAMESModel.FK__DonHang__ID_DV__4316F928", "DichVu", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyCYBERGAMESModel", "FK__DonHang__ID_Khac__4222D4EF", "TaiKhoan")]
        public TaiKhoan TaiKhoan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TaiKhoan>("QuanLyCYBERGAMESModel.FK__DonHang__ID_Khac__4222D4EF", "TaiKhoan").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TaiKhoan>("QuanLyCYBERGAMESModel.FK__DonHang__ID_Khac__4222D4EF", "TaiKhoan").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TaiKhoan> TaiKhoanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TaiKhoan>("QuanLyCYBERGAMESModel.FK__DonHang__ID_Khac__4222D4EF", "TaiKhoan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TaiKhoan>("QuanLyCYBERGAMESModel.FK__DonHang__ID_Khac__4222D4EF", "TaiKhoan", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyCYBERGAMESModel", Name="HoaDon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HoaDon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HoaDon object.
        /// </summary>
        /// <param name="iD_HoaDon">Initial value of the ID_HoaDon property.</param>
        public static HoaDon CreateHoaDon(global::System.String iD_HoaDon)
        {
            HoaDon hoaDon = new HoaDon();
            hoaDon.ID_HoaDon = iD_HoaDon;
            return hoaDon;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_HoaDon
        {
            get
            {
                return _ID_HoaDon;
            }
            set
            {
                if (_ID_HoaDon != value)
                {
                    OnID_HoaDonChanging(value);
                    ReportPropertyChanging("ID_HoaDon");
                    _ID_HoaDon = StructuralObject.SetValidValue(value, false, "ID_HoaDon");
                    ReportPropertyChanged("ID_HoaDon");
                    OnID_HoaDonChanged();
                }
            }
        }
        private global::System.String _ID_HoaDon;
        partial void OnID_HoaDonChanging(global::System.String value);
        partial void OnID_HoaDonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID_TTDV
        {
            get
            {
                return _ID_TTDV;
            }
            set
            {
                OnID_TTDVChanging(value);
                ReportPropertyChanging("ID_TTDV");
                _ID_TTDV = StructuralObject.SetValidValue(value, true, "ID_TTDV");
                ReportPropertyChanged("ID_TTDV");
                OnID_TTDVChanged();
            }
        }
        private global::System.String _ID_TTDV;
        partial void OnID_TTDVChanging(global::System.String value);
        partial void OnID_TTDVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID_May
        {
            get
            {
                return _ID_May;
            }
            set
            {
                OnID_MayChanging(value);
                ReportPropertyChanging("ID_May");
                _ID_May = StructuralObject.SetValidValue(value, true, "ID_May");
                ReportPropertyChanged("ID_May");
                OnID_MayChanged();
            }
        }
        private global::System.String _ID_May;
        partial void OnID_MayChanging(global::System.String value);
        partial void OnID_MayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ThoiGianMo
        {
            get
            {
                return _ThoiGianMo;
            }
            set
            {
                OnThoiGianMoChanging(value);
                ReportPropertyChanging("ThoiGianMo");
                _ThoiGianMo = StructuralObject.SetValidValue(value, "ThoiGianMo");
                ReportPropertyChanged("ThoiGianMo");
                OnThoiGianMoChanged();
            }
        }
        private Nullable<global::System.DateTime> _ThoiGianMo;
        partial void OnThoiGianMoChanging(Nullable<global::System.DateTime> value);
        partial void OnThoiGianMoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ThoiGianTat
        {
            get
            {
                return _ThoiGianTat;
            }
            set
            {
                OnThoiGianTatChanging(value);
                ReportPropertyChanging("ThoiGianTat");
                _ThoiGianTat = StructuralObject.SetValidValue(value, "ThoiGianTat");
                ReportPropertyChanged("ThoiGianTat");
                OnThoiGianTatChanged();
            }
        }
        private Nullable<global::System.DateTime> _ThoiGianTat;
        partial void OnThoiGianTatChanging(Nullable<global::System.DateTime> value);
        partial void OnThoiGianTatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TongTien
        {
            get
            {
                return _TongTien;
            }
            set
            {
                OnTongTienChanging(value);
                ReportPropertyChanging("TongTien");
                _TongTien = StructuralObject.SetValidValue(value, "TongTien");
                ReportPropertyChanged("TongTien");
                OnTongTienChanged();
            }
        }
        private Nullable<global::System.Decimal> _TongTien;
        partial void OnTongTienChanging(Nullable<global::System.Decimal> value);
        partial void OnTongTienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TinhTrangHD
        {
            get
            {
                return _TinhTrangHD;
            }
            set
            {
                OnTinhTrangHDChanging(value);
                ReportPropertyChanging("TinhTrangHD");
                _TinhTrangHD = StructuralObject.SetValidValue(value, true, "TinhTrangHD");
                ReportPropertyChanged("TinhTrangHD");
                OnTinhTrangHDChanged();
            }
        }
        private global::System.String _TinhTrangHD;
        partial void OnTinhTrangHDChanging(global::System.String value);
        partial void OnTinhTrangHDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID_KhachHang
        {
            get
            {
                return _ID_KhachHang;
            }
            set
            {
                OnID_KhachHangChanging(value);
                ReportPropertyChanging("ID_KhachHang");
                _ID_KhachHang = StructuralObject.SetValidValue(value, true, "ID_KhachHang");
                ReportPropertyChanged("ID_KhachHang");
                OnID_KhachHangChanged();
            }
        }
        private global::System.String _ID_KhachHang;
        partial void OnID_KhachHangChanging(global::System.String value);
        partial void OnID_KhachHangChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyCYBERGAMESModel", "FK__HoaDon__ID_Khach__48CFD27E", "TaiKhoan")]
        public TaiKhoan TaiKhoan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TaiKhoan>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_Khach__48CFD27E", "TaiKhoan").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TaiKhoan>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_Khach__48CFD27E", "TaiKhoan").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TaiKhoan> TaiKhoanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TaiKhoan>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_Khach__48CFD27E", "TaiKhoan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TaiKhoan>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_Khach__48CFD27E", "TaiKhoan", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyCYBERGAMESModel", "FK__HoaDon__ID_May__4AB81AF0", "May")]
        public May May
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<May>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_May__4AB81AF0", "May").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<May>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_May__4AB81AF0", "May").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<May> MayReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<May>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_May__4AB81AF0", "May");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<May>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_May__4AB81AF0", "May", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyCYBERGAMESModel", "FK__HoaDon__ID_TTDV__49C3F6B7", "ThanhToanDV")]
        public ThanhToanDV ThanhToanDV
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ThanhToanDV>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_TTDV__49C3F6B7", "ThanhToanDV").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ThanhToanDV>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_TTDV__49C3F6B7", "ThanhToanDV").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ThanhToanDV> ThanhToanDVReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ThanhToanDV>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_TTDV__49C3F6B7", "ThanhToanDV");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ThanhToanDV>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_TTDV__49C3F6B7", "ThanhToanDV", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyCYBERGAMESModel", Name="Kho")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Kho : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Kho object.
        /// </summary>
        /// <param name="iD_Mathang">Initial value of the ID_Mathang property.</param>
        public static Kho CreateKho(global::System.String iD_Mathang)
        {
            Kho kho = new Kho();
            kho.ID_Mathang = iD_Mathang;
            return kho;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Mathang
        {
            get
            {
                return _ID_Mathang;
            }
            set
            {
                if (_ID_Mathang != value)
                {
                    OnID_MathangChanging(value);
                    ReportPropertyChanging("ID_Mathang");
                    _ID_Mathang = StructuralObject.SetValidValue(value, false, "ID_Mathang");
                    ReportPropertyChanged("ID_Mathang");
                    OnID_MathangChanged();
                }
            }
        }
        private global::System.String _ID_Mathang;
        partial void OnID_MathangChanging(global::System.String value);
        partial void OnID_MathangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenMatHang
        {
            get
            {
                return _TenMatHang;
            }
            set
            {
                OnTenMatHangChanging(value);
                ReportPropertyChanging("TenMatHang");
                _TenMatHang = StructuralObject.SetValidValue(value, true, "TenMatHang");
                ReportPropertyChanged("TenMatHang");
                OnTenMatHangChanged();
            }
        }
        private global::System.String _TenMatHang;
        partial void OnTenMatHangChanging(global::System.String value);
        partial void OnTenMatHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SoLuong
        {
            get
            {
                return _SoLuong;
            }
            set
            {
                OnSoLuongChanging(value);
                ReportPropertyChanging("SoLuong");
                _SoLuong = StructuralObject.SetValidValue(value, true, "SoLuong");
                ReportPropertyChanged("SoLuong");
                OnSoLuongChanged();
            }
        }
        private global::System.String _SoLuong;
        partial void OnSoLuongChanging(global::System.String value);
        partial void OnSoLuongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TinhTrang
        {
            get
            {
                return _TinhTrang;
            }
            set
            {
                OnTinhTrangChanging(value);
                ReportPropertyChanging("TinhTrang");
                _TinhTrang = StructuralObject.SetValidValue(value, true, "TinhTrang");
                ReportPropertyChanged("TinhTrang");
                OnTinhTrangChanged();
            }
        }
        private global::System.String _TinhTrang;
        partial void OnTinhTrangChanging(global::System.String value);
        partial void OnTinhTrangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayNhap
        {
            get
            {
                return _NgayNhap;
            }
            set
            {
                OnNgayNhapChanging(value);
                ReportPropertyChanging("NgayNhap");
                _NgayNhap = StructuralObject.SetValidValue(value, "NgayNhap");
                ReportPropertyChanged("NgayNhap");
                OnNgayNhapChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayNhap;
        partial void OnNgayNhapChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayNhapChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyCYBERGAMESModel", "FK__DichVu__ID_Matha__3F466844", "DichVu")]
        public EntityCollection<DichVu> DichVus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DichVu>("QuanLyCYBERGAMESModel.FK__DichVu__ID_Matha__3F466844", "DichVu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DichVu>("QuanLyCYBERGAMESModel.FK__DichVu__ID_Matha__3F466844", "DichVu", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyCYBERGAMESModel", Name="May")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class May : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new May object.
        /// </summary>
        /// <param name="iD_May">Initial value of the ID_May property.</param>
        public static May CreateMay(global::System.String iD_May)
        {
            May may = new May();
            may.ID_May = iD_May;
            return may;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_May
        {
            get
            {
                return _ID_May;
            }
            set
            {
                if (_ID_May != value)
                {
                    OnID_MayChanging(value);
                    ReportPropertyChanging("ID_May");
                    _ID_May = StructuralObject.SetValidValue(value, false, "ID_May");
                    ReportPropertyChanged("ID_May");
                    OnID_MayChanged();
                }
            }
        }
        private global::System.String _ID_May;
        partial void OnID_MayChanging(global::System.String value);
        partial void OnID_MayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenMay
        {
            get
            {
                return _TenMay;
            }
            set
            {
                OnTenMayChanging(value);
                ReportPropertyChanging("TenMay");
                _TenMay = StructuralObject.SetValidValue(value, true, "TenMay");
                ReportPropertyChanged("TenMay");
                OnTenMayChanged();
            }
        }
        private global::System.String _TenMay;
        partial void OnTenMayChanging(global::System.String value);
        partial void OnTenMayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TinhTrangMay
        {
            get
            {
                return _TinhTrangMay;
            }
            set
            {
                OnTinhTrangMayChanging(value);
                ReportPropertyChanging("TinhTrangMay");
                _TinhTrangMay = StructuralObject.SetValidValue(value, true, "TinhTrangMay");
                ReportPropertyChanged("TinhTrangMay");
                OnTinhTrangMayChanged();
            }
        }
        private global::System.String _TinhTrangMay;
        partial void OnTinhTrangMayChanging(global::System.String value);
        partial void OnTinhTrangMayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID_gia
        {
            get
            {
                return _ID_gia;
            }
            set
            {
                OnID_giaChanging(value);
                ReportPropertyChanging("ID_gia");
                _ID_gia = StructuralObject.SetValidValue(value, true, "ID_gia");
                ReportPropertyChanged("ID_gia");
                OnID_giaChanged();
            }
        }
        private global::System.String _ID_gia;
        partial void OnID_giaChanging(global::System.String value);
        partial void OnID_giaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> HoatDong
        {
            get
            {
                return _HoatDong;
            }
            set
            {
                OnHoatDongChanging(value);
                ReportPropertyChanging("HoatDong");
                _HoatDong = StructuralObject.SetValidValue(value, "HoatDong");
                ReportPropertyChanged("HoatDong");
                OnHoatDongChanged();
            }
        }
        private Nullable<global::System.Boolean> _HoatDong;
        partial void OnHoatDongChanging(Nullable<global::System.Boolean> value);
        partial void OnHoatDongChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyCYBERGAMESModel", "FK__May__ID_gia__3A81B327", "DonGia")]
        public DonGia DonGia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DonGia>("QuanLyCYBERGAMESModel.FK__May__ID_gia__3A81B327", "DonGia").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DonGia>("QuanLyCYBERGAMESModel.FK__May__ID_gia__3A81B327", "DonGia").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DonGia> DonGiaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DonGia>("QuanLyCYBERGAMESModel.FK__May__ID_gia__3A81B327", "DonGia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DonGia>("QuanLyCYBERGAMESModel.FK__May__ID_gia__3A81B327", "DonGia", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyCYBERGAMESModel", "FK__HoaDon__ID_May__4AB81AF0", "HoaDon")]
        public EntityCollection<HoaDon> HoaDons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HoaDon>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_May__4AB81AF0", "HoaDon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HoaDon>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_May__4AB81AF0", "HoaDon", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyCYBERGAMESModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyCYBERGAMESModel", Name="TaiKhoan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TaiKhoan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TaiKhoan object.
        /// </summary>
        /// <param name="iD_KhachHang">Initial value of the ID_KhachHang property.</param>
        public static TaiKhoan CreateTaiKhoan(global::System.String iD_KhachHang)
        {
            TaiKhoan taiKhoan = new TaiKhoan();
            taiKhoan.ID_KhachHang = iD_KhachHang;
            return taiKhoan;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_KhachHang
        {
            get
            {
                return _ID_KhachHang;
            }
            set
            {
                if (_ID_KhachHang != value)
                {
                    OnID_KhachHangChanging(value);
                    ReportPropertyChanging("ID_KhachHang");
                    _ID_KhachHang = StructuralObject.SetValidValue(value, false, "ID_KhachHang");
                    ReportPropertyChanged("ID_KhachHang");
                    OnID_KhachHangChanged();
                }
            }
        }
        private global::System.String _ID_KhachHang;
        partial void OnID_KhachHangChanging(global::System.String value);
        partial void OnID_KhachHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenKhachHang
        {
            get
            {
                return _TenKhachHang;
            }
            set
            {
                OnTenKhachHangChanging(value);
                ReportPropertyChanging("TenKhachHang");
                _TenKhachHang = StructuralObject.SetValidValue(value, true, "TenKhachHang");
                ReportPropertyChanged("TenKhachHang");
                OnTenKhachHangChanged();
            }
        }
        private global::System.String _TenKhachHang;
        partial void OnTenKhachHangChanging(global::System.String value);
        partial void OnTenKhachHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SDT
        {
            get
            {
                return _SDT;
            }
            set
            {
                OnSDTChanging(value);
                ReportPropertyChanging("SDT");
                _SDT = StructuralObject.SetValidValue(value, true, "SDT");
                ReportPropertyChanged("SDT");
                OnSDTChanged();
            }
        }
        private global::System.String _SDT;
        partial void OnSDTChanging(global::System.String value);
        partial void OnSDTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> GioiTinh
        {
            get
            {
                return _GioiTinh;
            }
            set
            {
                OnGioiTinhChanging(value);
                ReportPropertyChanging("GioiTinh");
                _GioiTinh = StructuralObject.SetValidValue(value, "GioiTinh");
                ReportPropertyChanged("GioiTinh");
                OnGioiTinhChanged();
            }
        }
        private Nullable<global::System.Boolean> _GioiTinh;
        partial void OnGioiTinhChanging(Nullable<global::System.Boolean> value);
        partial void OnGioiTinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ThoiGianGiaNhap
        {
            get
            {
                return _ThoiGianGiaNhap;
            }
            set
            {
                OnThoiGianGiaNhapChanging(value);
                ReportPropertyChanging("ThoiGianGiaNhap");
                _ThoiGianGiaNhap = StructuralObject.SetValidValue(value, "ThoiGianGiaNhap");
                ReportPropertyChanged("ThoiGianGiaNhap");
                OnThoiGianGiaNhapChanged();
            }
        }
        private Nullable<global::System.DateTime> _ThoiGianGiaNhap;
        partial void OnThoiGianGiaNhapChanging(Nullable<global::System.DateTime> value);
        partial void OnThoiGianGiaNhapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LoaiKhachHang
        {
            get
            {
                return _LoaiKhachHang;
            }
            set
            {
                OnLoaiKhachHangChanging(value);
                ReportPropertyChanging("LoaiKhachHang");
                _LoaiKhachHang = StructuralObject.SetValidValue(value, true, "LoaiKhachHang");
                ReportPropertyChanged("LoaiKhachHang");
                OnLoaiKhachHangChanged();
            }
        }
        private global::System.String _LoaiKhachHang;
        partial void OnLoaiKhachHangChanging(global::System.String value);
        partial void OnLoaiKhachHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenDN
        {
            get
            {
                return _TenDN;
            }
            set
            {
                OnTenDNChanging(value);
                ReportPropertyChanging("TenDN");
                _TenDN = StructuralObject.SetValidValue(value, true, "TenDN");
                ReportPropertyChanged("TenDN");
                OnTenDNChanged();
            }
        }
        private global::System.String _TenDN;
        partial void OnTenDNChanging(global::System.String value);
        partial void OnTenDNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Matkhau
        {
            get
            {
                return _Matkhau;
            }
            set
            {
                OnMatkhauChanging(value);
                ReportPropertyChanging("Matkhau");
                _Matkhau = StructuralObject.SetValidValue(value, true, "Matkhau");
                ReportPropertyChanged("Matkhau");
                OnMatkhauChanged();
            }
        }
        private global::System.String _Matkhau;
        partial void OnMatkhauChanging(global::System.String value);
        partial void OnMatkhauChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> GiaMay
        {
            get
            {
                return _GiaMay;
            }
            set
            {
                OnGiaMayChanging(value);
                ReportPropertyChanging("GiaMay");
                _GiaMay = StructuralObject.SetValidValue(value, "GiaMay");
                ReportPropertyChanged("GiaMay");
                OnGiaMayChanged();
            }
        }
        private Nullable<global::System.Decimal> _GiaMay;
        partial void OnGiaMayChanging(Nullable<global::System.Decimal> value);
        partial void OnGiaMayChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyCYBERGAMESModel", "FK__DonHang__ID_Khac__4222D4EF", "DonHang")]
        public EntityCollection<DonHang> DonHangs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DonHang>("QuanLyCYBERGAMESModel.FK__DonHang__ID_Khac__4222D4EF", "DonHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DonHang>("QuanLyCYBERGAMESModel.FK__DonHang__ID_Khac__4222D4EF", "DonHang", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyCYBERGAMESModel", "FK__HoaDon__ID_Khach__48CFD27E", "HoaDon")]
        public EntityCollection<HoaDon> HoaDons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HoaDon>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_Khach__48CFD27E", "HoaDon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HoaDon>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_Khach__48CFD27E", "HoaDon", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyCYBERGAMESModel", "FK__ThanhToan__ID_Kh__45F365D3", "ThanhToanDV")]
        public EntityCollection<ThanhToanDV> ThanhToanDVs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ThanhToanDV>("QuanLyCYBERGAMESModel.FK__ThanhToan__ID_Kh__45F365D3", "ThanhToanDV");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ThanhToanDV>("QuanLyCYBERGAMESModel.FK__ThanhToan__ID_Kh__45F365D3", "ThanhToanDV", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyCYBERGAMESModel", Name="ThanhToanDV")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ThanhToanDV : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ThanhToanDV object.
        /// </summary>
        /// <param name="iD_TTDV">Initial value of the ID_TTDV property.</param>
        public static ThanhToanDV CreateThanhToanDV(global::System.String iD_TTDV)
        {
            ThanhToanDV thanhToanDV = new ThanhToanDV();
            thanhToanDV.ID_TTDV = iD_TTDV;
            return thanhToanDV;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_TTDV
        {
            get
            {
                return _ID_TTDV;
            }
            set
            {
                if (_ID_TTDV != value)
                {
                    OnID_TTDVChanging(value);
                    ReportPropertyChanging("ID_TTDV");
                    _ID_TTDV = StructuralObject.SetValidValue(value, false, "ID_TTDV");
                    ReportPropertyChanged("ID_TTDV");
                    OnID_TTDVChanged();
                }
            }
        }
        private global::System.String _ID_TTDV;
        partial void OnID_TTDVChanging(global::System.String value);
        partial void OnID_TTDVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID_KhachHang
        {
            get
            {
                return _ID_KhachHang;
            }
            set
            {
                OnID_KhachHangChanging(value);
                ReportPropertyChanging("ID_KhachHang");
                _ID_KhachHang = StructuralObject.SetValidValue(value, true, "ID_KhachHang");
                ReportPropertyChanged("ID_KhachHang");
                OnID_KhachHangChanged();
            }
        }
        private global::System.String _ID_KhachHang;
        partial void OnID_KhachHangChanging(global::System.String value);
        partial void OnID_KhachHangChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyCYBERGAMESModel", "FK__HoaDon__ID_TTDV__49C3F6B7", "HoaDon")]
        public EntityCollection<HoaDon> HoaDons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HoaDon>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_TTDV__49C3F6B7", "HoaDon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HoaDon>("QuanLyCYBERGAMESModel.FK__HoaDon__ID_TTDV__49C3F6B7", "HoaDon", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyCYBERGAMESModel", "FK__ThanhToan__ID_Kh__45F365D3", "TaiKhoan")]
        public TaiKhoan TaiKhoan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TaiKhoan>("QuanLyCYBERGAMESModel.FK__ThanhToan__ID_Kh__45F365D3", "TaiKhoan").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TaiKhoan>("QuanLyCYBERGAMESModel.FK__ThanhToan__ID_Kh__45F365D3", "TaiKhoan").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TaiKhoan> TaiKhoanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TaiKhoan>("QuanLyCYBERGAMESModel.FK__ThanhToan__ID_Kh__45F365D3", "TaiKhoan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TaiKhoan>("QuanLyCYBERGAMESModel.FK__ThanhToan__ID_Kh__45F365D3", "TaiKhoan", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
